Пришёл, увидел, загрузил (часть 1)
htmlacademy-ecmascript/267675-big-trip-18 pull request #14
Opened 2022-09-17 17:32 UTC by valek00794

2022-09-19 08:20 UTC, Dima-Dim requested changes

2022-09-19 08:20 UTC, Dima-Dim commented on src/view/edit-point-view.js
> +        destName = dest.name;
Почему в подобных вместо подобных конструкциях не используешь методы массива? Например, `find`.

2022-09-19 17:16 UTC, valek00794 commented on src/view/edit-point-view.js
> +        destName = dest.name;
Решаю задачу в лоб, методы не сразу всплывают в голове. Зарефакторил в последнем коммите. Код стал намного чище, спасибо

2022-09-21 15:04 UTC, Dima-Dim requested changes
https://htmlacademy-ecmascript.github.io/267675-big-trip-18/14/ - при открытии карточки на редактировании и сохранении ошибка в консоли:
```
Uncaught (in promise) Error: Can't update point
    at points-model.js:69:13
    at s (points-model.js:2:1)
    at Generator._invoke (points-model.js:2:1)
    at Generator.next (points-model.js:2:1)
    at Go (points-model.js:2:1)
    at a (points-model.js:2:1)
```

2022-09-23 12:14 UTC, merged